# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20160703_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.IntegerField(choices=[(1, 'Python 3'), (2, 'C++')], default=1),
        ),
    ]
