# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_program_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.IntegerField(choices=[(1, 'Python 3'), (2, 'C++')], default=1),
        ),
    ]
